apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
  namespace: bandwidth-monitor
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
      - name: backend
        image: bandwidth-backend:latest
        imagePullPolicy: Never  # For local development
        ports:
        - containerPort: 4000
        env:
        - name: NODE_ENV
          valueFrom:
            configMapKeyRef:
              name: bandwidth-config
              key: NODE_ENV
        - name: PORT
          value: "4000"
        - name: INFLUXDB_URL
          value: "http://influxdb:8086"
        - name: REDIS_URL
          value: "redis://redis:6379"
        - name: INFLUXDB_USERNAME
          valueFrom:
            secretKeyRef:
              name: bandwidth-secrets
              key: INFLUXDB_USERNAME
        - name: INFLUXDB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: bandwidth-secrets
              key: INFLUXDB_PASSWORD
        - name: INFLUXDB_ORG
          valueFrom:
            secretKeyRef:
              name: bandwidth-secrets
              key: INFLUXDB_ORG
        - name: INFLUXDB_BUCKET
          valueFrom:
            secretKeyRef:
              name: bandwidth-secrets
              key: INFLUXDB_BUCKET
        - name: INFLUXDB_TOKEN
          valueFrom:
            secretKeyRef:
              name: bandwidth-secrets
              key: INFLUXDB_TOKEN
        - name: SENDGRID_API_KEY
          valueFrom:
            secretKeyRef:
              name: bandwidth-secrets
              key: SENDGRID_API_KEY
        - name: VAPID_PUBLIC_KEY
          valueFrom:
            secretKeyRef:
              name: bandwidth-secrets
              key: VAPID_PUBLIC_KEY
        - name: VAPID_PRIVATE_KEY
          valueFrom:
            secretKeyRef:
              name: bandwidth-secrets
              key: VAPID_PRIVATE_KEY
        - name: DROP_THRESHOLD_MBPS
          valueFrom:
            configMapKeyRef:
              name: bandwidth-config
              key: DROP_THRESHOLD_MBPS
        - name: DROP_DETECTION_WINDOW_SECONDS
          valueFrom:
            configMapKeyRef:
              name: bandwidth-config
              key: DROP_DETECTION_WINDOW_SECONDS
        - name: DROP_DURATION_THRESHOLD_SECONDS
          valueFrom:
            configMapKeyRef:
              name: bandwidth-config
              key: DROP_DURATION_THRESHOLD_SECONDS
        - name: ALERT_ADVANCE_MINUTES
          valueFrom:
            configMapKeyRef:
              name: bandwidth-config
              key: ALERT_ADVANCE_MINUTES
        resources:
          requests:
            memory: "128Mi"
            cpu: "100m"
          limits:
            memory: "256Mi"
            cpu: "200m"
        livenessProbe:
          httpGet:
            path: /health
            port: 4000
          initialDelaySeconds: 30
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /health
            port: 4000
          initialDelaySeconds: 5
          periodSeconds: 5
---
apiVersion: v1
kind: Service
metadata:
  name: backend
  namespace: bandwidth-monitor
spec:
  selector:
    app: backend
  ports:
  - port: 4000
    targetPort: 4000
  type: ClusterIP 